# $Id: Makefile,v 1.36 2009/09/21 17:02:44 mascarenhas Exp $

T= lfs

CONFIG= ./config

include $(CONFIG)

SRCS= src/$T.c
OBJS= src/$T.o

lib: src/lfs.dll

src/lfs.dll: $(OBJS)
	$(CC) $(LIB_OPTION) -o src/lfs.dll $(OBJS) -L$(LUA_LIBDIR) -llua

test: lib
	LUA_CPATH=./src/?.dll lua tests/test.lua

install:
	mkdir -p $(LUA_LIBDIR)
	cp src/lfs.dll $(LUA_LIBDIR)

clean:
	rm -f src/lfs.dll $(OBJS)
